"""initial_schema

Revision ID: 65e1286bfeaf
Revises: 
Create Date: 2026-03-17 23:43:45.722864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e1286bfeaf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('supabase_uid', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('profile_photo', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('passenger', 'driver', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('supabase_uid')
    )
    op.create_index('idx_users_supabase_uid', 'users', ['supabase_uid'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_make', sa.String(length=50), nullable=False),
    sa.Column('vehicle_model', sa.String(length=100), nullable=False),
    sa.Column('vehicle_type', sa.String(length=30), nullable=False),
    sa.Column('vehicle_color', sa.String(length=30), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('seat_capacity', sa.Integer(), nullable=False),
    sa.Column('mileage_kmpl', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("vehicle_type IN ('sedan', 'suv', 'hatchback', 'mini_bus')", name='ck_drivers_vehicle_type'),
    sa.CheckConstraint("verification_status IN ('pending', 'approved', 'rejected')", name='ck_drivers_verification_status'),
    sa.CheckConstraint('mileage_kmpl BETWEEN 1 AND 50', name='ck_drivers_mileage'),
    sa.CheckConstraint('seat_capacity BETWEEN 1 AND 8', name='ck_drivers_seat_capacity'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_drivers_status', 'drivers', ['verification_status'], unique=False)
    op.create_index('idx_drivers_user_id', 'drivers', ['user_id'], unique=False)
    op.create_table('driver_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_type IN ('license', 'rc_book', 'insurance', 'permit')", name='ck_driver_docs_type'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_driver_docs_status'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rides',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('source_address', sa.Text(), nullable=False),
    sa.Column('source_lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('source_lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('source_city', sa.String(length=100), nullable=True),
    sa.Column('dest_address', sa.Text(), nullable=False),
    sa.Column('dest_lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('dest_lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('dest_city', sa.String(length=100), nullable=True),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('total_distance_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('route_geometry', sa.Text(), nullable=True),
    sa.Column('total_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('per_seat_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'departed', 'completed', 'cancelled')", name='ck_rides_status'),
    sa.CheckConstraint('available_seats >= 0 AND available_seats <= total_seats', name='ck_rides_available_seats'),
    sa.CheckConstraint('total_seats BETWEEN 1 AND 8', name='ck_rides_total_seats'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rides_dest_geo', 'rides', ['dest_lat', 'dest_lng'], unique=False)
    op.create_index('idx_rides_driver_id', 'rides', ['driver_id'], unique=False)
    op.create_index('idx_rides_search', 'rides', ['status', 'departure_time'], unique=False, postgresql_where="status = 'active'")
    op.create_index('idx_rides_source_geo', 'rides', ['source_lat', 'source_lng'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_wallets_balance'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('seats_booked', sa.Integer(), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('pickup_lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('pickup_lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('dropoff_address', sa.Text(), nullable=True),
    sa.Column('dropoff_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('dropoff_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('confirmed', 'cancelled', 'completed')", name='ck_bookings_status'),
    sa.CheckConstraint('seats_booked BETWEEN 1 AND 4', name='ck_bookings_seats'),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bookings_passenger_id', 'bookings', ['passenger_id'], unique=False)
    op.create_index('idx_bookings_ride_id', 'bookings', ['ride_id'], unique=False)
    op.create_index('idx_bookings_unique_active', 'bookings', ['ride_id', 'passenger_id'], unique=True, postgresql_where="status = 'confirmed'")
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=True),
    sa.Column('toll_proof_url', sa.Text(), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_wallet_txns_status'),
    sa.CheckConstraint("type IN ('cashback_request', 'cashback_credited', 'cashback_rejected','withdrawal_request', 'withdrawal_approved', 'withdrawal_rejected')", name='ck_wallet_txns_type'),
    sa.CheckConstraint('amount > 0', name='ck_wallet_txns_amount'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wallet_txns_status', 'wallet_transactions', ['status'], unique=False)
    op.create_index('idx_wallet_txns_type', 'wallet_transactions', ['type'], unique=False)
    op.create_index('idx_wallet_txns_wallet_id', 'wallet_transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wallet_txns_wallet_id', table_name='wallet_transactions')
    op.drop_index('idx_wallet_txns_type', table_name='wallet_transactions')
    op.drop_index('idx_wallet_txns_status', table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index('idx_bookings_unique_active', table_name='bookings', postgresql_where="status = 'confirmed'")
    op.drop_index('idx_bookings_ride_id', table_name='bookings')
    op.drop_index('idx_bookings_passenger_id', table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('wallets')
    op.drop_index('idx_rides_source_geo', table_name='rides')
    op.drop_index('idx_rides_search', table_name='rides', postgresql_where="status = 'active'")
    op.drop_index('idx_rides_driver_id', table_name='rides')
    op.drop_index('idx_rides_dest_geo', table_name='rides')
    op.drop_table('rides')
    op.drop_table('driver_documents')
    op.drop_index('idx_drivers_user_id', table_name='drivers')
    op.drop_index('idx_drivers_status', table_name='drivers')
    op.drop_table('drivers')
    op.drop_index('idx_users_supabase_uid', table_name='users')
    op.drop_table('users')
    op.drop_table('platform_config')
    # ### end Alembic commands ###